FROM python:3.12-slim

WORKDIR /app

# Instalar dependencias del sistema requeridas para algunas librerías (XGBoost)
RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Exponer el puerto
EXPOSE 8000

# Comando para ejecutar el servidor
CMD ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8000"]
